Sprint 12
Andrewsorokin13/ImageFeed pull request #5
Opened 2023-04-14 21:30 UTC by Andrewsorokin13

2023-04-15 16:14 UTC, protos17 requested changes

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/ImagesList/ImagesListCell.swift
> +    @IBAction func likeButtonClicked(_ sender: UIButton) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/ImagesList/ImagesListViewController.swift
> +            [weak self] _ in
[weak self] _ in рекомендую перенести на строку выше

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/ImagesList/ImagesListViewController.swift
>              guard let image = UIImage(named: Constants.ImageButton.noActiveLikeButtonImage) else { return UIImage()}
Код дублируется, не рекомендую использовать switch для кейсов true и false, здесь лучше использовать тернарный оператор

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/ImagesList/ImagesListViewController.swift
> +        imageListService.changeLike(photoId: photo.id, isLike: photo.isLiked) { result  in
Сильная ссылка, необходимо добавить weak self

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/SplashViewController/SplashViewPresenter.swift
> +    func verificationToken() {
Функции принято называть с помощью глаголов:
verificateToken()

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/Profile/ProfilePresenter.swift
> +       if oauth2TokenStorage.deleteToken {
Здесь должен вызываться алерт, только при нажатии на кнопку "Да" уже происходить выход из профиля

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/Profile/ProfileViewController.swift
> +            avatarImageView.topAnchor.constraint(equalTo: view.topAnchor, constant: 76),
Здесь должны использовать view.safeAreaLayoutGuide.topAnchor, constant: 32

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/Profile/ProfileViewController.swift
> +            nameLable.heightAnchor.constraint(equalToConstant: 18),
Для лейблов высоту можно не ставить, она будет высчитываться автоматически

2023-04-15 16:14 UTC, protos17 commented on ImageFeed/ViewController/SingleImage/ImageViewPresenter.swift
> +                print(error)
Рекомендую показать алерт с ошибкой или вызвать assertionFailure

2023-04-17 15:33 UTC, Andrewsorokin13 commented on ImageFeed/ServiceAccessLayer/ImagesListService/ImagesListService.swift
> +        let formatter = ISO8601DateFormatter()
@protos17 
Окей, спасибо

2023-04-18 10:00 UTC, protos17 approved these changes

2023-04-18 10:00 UTC, protos17 commented on ImageFeed/ViewController/WebViewViewController/WebViewViewController.swift
> +            progressView.heightAnchor.constraint(equalToConstant: 1),
Рекомендую сделать чуть побольше, чтобы был отчетливо виден

2023-04-18 12:29 UTC, merged